

debug: false

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:dm://192.168.204.111:5236?schema=SDPDBA&compatibleMode=oracle&useUnicode=true&characterEncoding=UTF-8
    username: ${SDP_DB_USERNAME:sdpdba}
    password: ${SDP_DB_PASSWORD:Szh_Software@617}
    driver-class-name: dm.jdbc.driver.DmDriver
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  data:
    redis:
      host: ${SDP_REDIS_HOST:127.0.0.1}
      port: ${SDP_REDIS_PORT:6379}
      database: 0

arthas:
  telnetPort: 13658
  httpPort: 18563

sa-token:
  token-name: satoken
  timeout: 86400
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false
